# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Q033WDDGXjs3sYebVS3Yg79TprhhoNF
"""

!pip install opencv-python-headless numpy pytesseract

!python clean_full_pages_script3.py